version: 2
jobs:
  build:
    working_directory: ~/beanstalk-dispatch
    docker:
        - image: themattrix/tox
    steps:
      - checkout
      - run: pyenv local 3.7 3.8 3.9 3.10 3.11 3.12
      - run: make installdeps
      - run: make lint && tox && codecov
